from app.api.v1 import manage
from app.api.v1 import auth
from app.api.v1 import profile
from app.api.v1 import upload
from app.api.v1 import battle
from app.api.v1 import cards
from app.api.v1 import test
from app.api.v1 import layouts
from app.api.v1 import layers
from app.api.v1 import points
